// auth
export const SAVE_AUTH_USER_DATA = "SAVE_AUTH_USER_DATA";

// alert
export const OPEN_ALERT_STATUS = "OPEN_ALERT_STATUS";
export const CLOSE_ALERT_REQUEST = "CLOSE_ALERT_REQUEST";


// server
export const USER_SERVERS_LIST = 'USER_SERVERS_LIST';
export const ADD_NEW_SERVER_TO_USER_JOINED = 'ADD_NEW_SERVER_TO_USER_JOINED';
// view
export const CHANGE_SERVER_VIEW = 'CHANGE_SERVER_VIEW';
export const CHANGE_CHANNEL_VIEW = 'CHANGE_CHANNEL_VIEW';

// channel
export const FETCH_SERVER_CHANNELS = 'FETCH_SERVER_CHANNELS';
export const ADD_CHANNEL_TO_SERVER = 'ADD_CHANNEL_TO_SERVER';

// message chat
export const SEND_MESSAGE_TO_CHANNEL = 'SEND_MESSAGE_TO_CHANNEL';
